import classNames from 'classnames'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Header } from '../components/Header'
import './globals.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          roboto.className,
          'min-h-screen flex flex-col relative bg-gray-light'
        )}
      >
        <Header />

        <main className="basis-1 grow">{children}</main>
      </body>
    </html>
  )
}
